### ISSUE TITLE
[BUG] E-stop fails runCore build

### ISSUE THREAD

**Issue by cooperbell** [UIOWA5830SP19/SPP100#11]
**Describe the bug**
Triggering the e-stop button on the dashboard appears to successfully stop the running program as shown in the terminal:

```
[2019/01/28 01:39:44.239 PM] networking_w: SOFTWARE ESTOP PRESSED
[2019/01/28 01:39:45.246 PM] arch_w: finished running tasks!
```

but then errors are thrown that say that the runCore task failed as shown in the terminal:
```
What went wrong:
Execution failed for task ':runCore'.
```

**To Reproduce**

**Expected behavior**
the runCore build doesn't fail

**Boat code or simulation code?**
boat

**Windows or Mac?**
both

**Recommended Investigation**
Look into why the runCore task is failing after the tasks have been successfully terminated. Maybe the code isn't there to gracefully terminate the program?

**Comment by aklinker1** [comment]
If I remember correctly I designed this to exit with a code of `Core.EXIT_CODE_SOFTWARE_ESTOP`. E-Stopping in my mind meant that there was a failure, and that if you press E-Stop, you should expect to see a failure. If this goes against what you prefer to happen, [here](https://github.com/UIOWA5830SP19/SPP100/blob/3bd0c96b1763a71bfb3bd72f9c824323509413e4/BoatOS/src/main/java/com/imarc/marc_i/network/requests/EStopHandler.java#L25) is the line you should change:

```java
// From 
Core.exit(Core.EXIT_CODE_SOFTWARE_ESTOP);

// To
Core.exit(Core.EXIT_CODE_SUCCESS);
```

**Comment by jwryan9** [comment]
Behaves as expected. Closing issue.
