### ISSUE TITLE
[BUG] Task Endpoint goes down before dashboard is able to get the last update

### ISSUE THREAD

**Issue by joshuawootonn** [UIOWA5830SP19/SPP100#112]
**Describe the bug**
Task Endpoint goes down before dashboard is able to get the last update

**To Reproduce**
* Run a test
* Wait for it's completion
* Look at task list

**Expected behavior**
Task List should show a completed test and highlight the exit task

**Screenshots**
This is what the task list currently looks like when a task has completed
![image](https://user-images.githubusercontent.com/20950876/55493858-4b4efd00-55ff-11e9-8fe8-0ad243f4defa.png)

**Boat code or simulation code?**
The Boat code shouldn't kill the node server that is communicating with the dashboard, so that the dashboard can get the change in status

**Comment by hhpatel09** [comment]
Impossible to do with the current setup of the backend
