### ISSUE TITLE
[TASK] Wiki Pages for Linting and Testing Decision

### ISSUE THREAD

**Issue by hhpatel09** [UIOWA5830SP19/SPP100#113]
### Description
 We are going to add wiki pages for the decision of linting and testing that is being done for the dashboard. 

### Estimated Effort
1

### Additional Notes
This is something that Professor Johnson mentioned.

**Comment by joshuawootonn** [comment]
Resolved by the creation of this page 
https://github.com/UIOWA5830SP19/SPP100/wiki/Design-Decisions
