### ISSUE TITLE
[FEATURE] Change boat icon in Dashboard

### ISSUE THREAD

**Issue by cooperbell** [UIOWA5830SP19/SPP100#114]
### Description
We would like the boat icon on the Dashboard to be changed from the current circle to an arrow to represent the angle of the boat. 

### Estimated Effort
2

### Additional Notes
It will take some investigation to see if the angle is being sent for the boatOS.

### Anything that could be affected by this? (N/A for nothing)
N/A

**Comment by joshuawootonn** [comment]
@hhpatel09 did you finish this the other day ?

**Comment by hhpatel09** [comment]
No
