### ISSUE TITLE
[BUG] Divide by 0 when boat and buoy are at latitude and longitude

### ISSUE THREAD

**Issue by cooperbell** [UIOWA5830SP19/SPP100#118]
**Describe the bug**
In [this](https://github.com/UIOWA5830SP19/SPP100/blob/b81d6f7515f56f30b5e5aa11c30effefd15670e8/BoatOS/src/main/java/com/imarc/marc_i/mapping/CounterClockwiseBuoy.java#L14) method, when the boat's GPS coords and the current buoy's GPS coords are the same, there will be a divide by 0.

**Expected behavior**
Should add 0 to vector field, not NaN

**Boat code or simulation code?**
Boat code

**Additional context** 
Check if there is going to be a divide by 0 and add 0 to the vector field, try to stay away from a try...catch block

**Comment by jwryan9** [comment]
Simple fix by adding an if statement to calculations.
