### ISSUE TITLE
[FEATURE] Create Lidar Simulation

### ISSUE THREAD

**Issue by cooperbell** [UIOWA5830SP19/SPP100#23]
### Description
Create a LidarSimluation class in com/imarc/marc_i/hardware that extends the Lidar class. 

### Estimated Effort
undefined

### Additional Notes
There's a LidarReal class you could look into for ideas on how to work with Lidar. ArduinoSim & CameraSim could also give you ideas for how to interact with the simulation

### Anything that could be affected by this? (N/A for nothing)
N/A

**Comment by cooperbell** [comment]
Out of scope for this class

**Comment by aklinker1** [comment]
Haha @cooperbell not feeling up to the math? 🤣

**Comment by cooperbell** [comment]
> Haha @cooperbell not feeling up to the math? 🤣

hahah not at the moment, I'll probably get into that in the summer
