### ISSUE TITLE
[TASK] Learn basics of ReactJS

### ISSUE THREAD

**Issue by hjmjohnson** [UIOWA5830SP19/SPP100#34]
### Description
@joshuawootonn please help @Nonovi learn the basics of react to help with the Dashboard.

### Estimated Effort
2

**Comment by hhpatel09** [comment]
I need to now learn ReactJS now as well. So I have added my self to this. I will try to learn on my own and with the help of Josh

**Comment by hhpatel09** [comment]
I have a solid understanding of Javascript. Now onto react.

**Comment by hhpatel09** [comment]
I have finished this. I now know react and only have to get a good understanding of typescript.
