### ISSUE TITLE
[BUG] Connect button on connect page doesn't work as intended

### ISSUE THREAD

**Issue by cooperbell** [UIOWA5830SP19/SPP100#38]
**Describe the bug**
When the boat code isn't running, the connect button does not let you into the dashboard. However, if you spam the button then it'll let you in. This probably isn't supposed to happen. I think the connect button isn't supposed to allow the redirect to the dashboard.

**To Reproduce**
1. Start Dashboard
2. Click on 'Connect'
3. Repeat 2 a bunch of times

**Expected behavior**
I think it would be nice for the connect button to let you in regardless if the boat code is running.

**Screenshots**

**Boat code or simulation code?**
simulation

**Windows or Mac?**

**Additional context**

**Comment by aklinker1** [comment]
> HAHA oh this one is funny. Not sure how that happened :rofl:
