### ISSUE TITLE
[FEATURE] Manual Control - Suspend all tasks for onManualControl()

### ISSUE THREAD

**Issue by cooperbell** [UIOWA5830SP19/SPP100#55]
### Description
When the Toggle Manual Controls checkbox is checked in the Dashboard, the boatOS should suspend current autonomous task and start onManualControl() task. 

### Estimated Effort
3

### Anything that could be affected by this? (N/A for nothing)
Suspending task could fail the gradle build

**Comment by jwryan9** [comment]
May not need to suspend tasks at all. Arduino ignores BoatOS as is when manually controlled. Would be more useful to restart task when you disable manual controls.

**Comment by jwryan9** [comment]
Is this considered done with the changes to manual controls?

**Comment by jwryan9** [comment]
Task is suspended properly when manual controls are toggled.
