### ISSUE TITLE
[FEATURE] Manual Controls Task - Correctly control boat's thrust 

### ISSUE THREAD

**Issue by cooperbell** [UIOWA5830SP19/SPP100#56]
### Description
When boatOS is running the manual controls task, it should be able to get the desired thrust percentages from the Dashboard and adjust the boat's thrust accordingly.

### Estimated Effort
3

### Anything that could be affected by this? (N/A for nothing)
N/A

**Comment by cooperbell** [comment]
While investigating #30 we saw in the Dashboard code that toggling manual controls opens up two sliders for the two thrusters -- fixing #30 could help us complete this

**Comment by jwryan9** [comment]
While investigating #30 it appears there is existing code for handling some form of dashboard based manual controls through http RESTful-esque API. Appears to be a somewhat well-built API for handling the dashboard as a whole. Code for manual controls specifically found [here](https://github.com/UIOWA5830SP19/SPP100/blob/development/BoatOS/src/main/java/com/imarc/marc_i/network/requests/ManualControlHandler.java)

**Comment by cooperbell** [comment]
> While investigating #30 we saw in the Dashboard code that toggling manual controls opens up two sliders for the two thrusters -- fixing #30 could identify if these sliders actually control the thrusters

sliders don't work :( An idea for implementing manual controls could be to make these sliders draggable with the mouse and have the values sent to the BoatOS

**Comment by jwryan9** [comment]
Closed with #132
