### ISSUE TITLE
[TASK] CI Pull Request

### ISSUE THREAD

**Issue by hhpatel09** [UIOWA5830SP19/SPP100#59]
### Description
Add pulling request to the CI

### Estimated Effort
1

**Comment by hhpatel09** [comment]
I found a better article to follow here:
https://ardalis.com/4-tips-to-integrate-teamcity-and-github

**Comment by hhpatel09** [comment]
I added a status bar at the top of the readme. This task is almost done. I think once the template is finished, we should be done. Currently, the build runs on every pull request but trying to make it show up better on GitHub interface. Shouldn't be more than a couple more hours of configuration.

**Comment by jwryan9** [comment]
Need to add running of unit tests to CI for both BoatOS and Dashboard.

**Comment by jwryan9** [comment]
Related to issue #54.

**Comment by jwryan9** [comment]
BoatOS CI is complete
