### ISSUE TITLE
[TASK] Dashboard CI

### ISSUE THREAD

**Issue by jwryan9** [UIOWA5830SP19/SPP100#63]
### Description
Setup CI for the Dashboard with Team City.

This CI will
* Run Testing
* Run Linting
and will indicate on the Team City dashboard whether these things failed or succeeded 

### Estimated Effort
2

**Comment by jwryan9** [comment]
Tests can be run in a CI environment using `CI=true npm test` from the Dashboard directory.

**Comment by jwryan9** [comment]
> Tests can be run in a CI environment using `CI=true npm test` from the Dashboard directory.

Similar thing should probably be done with `CI=true npm start` for other aspects of this issue.

**Comment by joshuawootonn** [comment]
> > Tests can be run in a CI environment using `CI=true npm test` from the Dashboard directory.
> 
> Similar thing should probably be done with `CI=true npm start` for other aspects of this issue.

**Comment by hhpatel09** [comment]
Instead of running the program as you mentioned above, @jwryan9, we would just build it with this command: `npm run build`
Also to run the test we are going to use the command: `CI=true npm run test`

**Comment by hhpatel09** [comment]
This is done and added on pull requests. Also tested for pull requests.

**Comment by jwryan9** [comment]
What is the PR number?
