### ISSUE TITLE
[TASK] Auth Files Encrypted Zip

### ISSUE THREAD

**Issue by jwryan9** [UIOWA5830SP19/SPP100#75]
### Description
Add two required auth files to encrypted zip and upload to repo. Include instructions to email team for requesting the password to zip file.

### Estimated Effort
0.5

### Additional Notes
Per @hhpatel09 conversation with @hjmjohnson.

**Comment by hhpatel09** [comment]
Added the file on the hub. Just need to write the wiki page now.

**Comment by hhpatel09** [comment]
* The wiki for this has been completed 
* This task is done
* We now need to fix the over-arching wiki page that links how to properly run everything for our project
