### ISSUE TITLE
[FEATURE] Create design documentation with the wiki

### ISSUE THREAD

**Issue by joshuawootonn** [UIOWA5830SP19/SPP100#81]
### Description
Right now we are just doing random things every week to create issues. This doc will give us a end goal and intermediate goals to hit along the way. 

It will include:
* All sprint goals
* Justifications for goals
* Mock of end product

### Estimated Effort
2

**Comment by joshuawootonn** [comment]
Finished a preliminary version of our goals for this semester [here](https://github.com/UIOWA5830SP19/SPP100/wiki/Dashboard-Design-Doc). If you guys could read through and ok it that would be great. Feel free to add or comment about anything that you think is missing.

**Comment by hhpatel09** [comment]
Read through this and looks good
